"""
Deterministic NoC mesh stitcher.

Problem this fixes: the top-level SoC is generated by a single LLM call
that is also expected to wire the router IPs into an actual mesh. Verified
empirically (see NOTES.md "NoC mesh top-level wiring is stubbed") that the
LLM does NOT attempt real per-node wiring for this - for a 4x3 (12-router)
hard-tier mesh it silently instantiated every router with ONLY clk/rst_n
connected, leaving every compass port, every local-SRAM AXI port, and
every NI link floating. This happened identically for both the original
broken router generator and the corrected gen_router_v2.py, so it is a
pre-existing top-level-generation gap, not something introduced by (or
fixed by) the router IP correction alone. Icarus does not flag unconnected
named ports as errors, so "elaborates cleanly" gave false confidence.

Fix: the mesh interconnect is fully mechanical/deterministic once the grid
dimensions are known - every router uses the same compass port convention
(p0=N, p1=S, p2=E, p3=W), every link follows the same master/slave pairing
rule, every node's local port always goes to that node's own NI + SRAM.
None of that requires architecture-specific judgment, so generate it in
Python instead of asking an LLM to hand-write 12 routers x 4 links worth
of repetitive port lists. This produces ONE self-contained Verilog module
(default name "noc_mesh") whose ONLY external ports are one AXI4-Lite
SLAVE port per node (so the CPU crossbar, a DMA engine's m_* master port,
etc. can be wired to whichever node(s) actually inject traffic - this is
the same kind of "connect this AXI master to this AXI slave, or tie idle"
task the LLM already handles correctly elsewhere in this same file, e.g.
DMA cfg ports - it is not asked to reason about mesh topology at all).
Every router<->router link, router<->local-SRAM AXI, and router<->local-NI
connection is wired internally and never exposed.

Each per-node NI's AXI4-Lite side is 32-bit (data_width defaults to 32,
matching the CPU/DMA-facing bus width throughout this SoC), while the
router/SRAM internal TileLink datapath is 64-bit. Connecting a narrower
net to a wider port is ordinary, well-defined Verilog: it zero-extends
without error. This does mean only the lower 32 bits of each 64-bit SRAM
word are ever written by CPU/DMA-originated traffic in this design - a
pre-existing width-domain characteristic of the organizer's own IP
generators (gen_tilelink_ni.py's DATA_W parameter drives both its AXI
side and its TileLink side with no way to decouple them; gen_axi_lite_sram.py
separately hardcodes a 4-bit wstrb regardless of its own data_width param),
not something introduced here.
"""
from gen_utils import hdr as _hdr

A_FIELD_WIDTHS = [
    ("opcode", 3), ("param", 3), ("size", 3), ("source", 4),
    ("addr", None), ("mask", None), ("data", None), ("valid", 1),
]
D_FIELD_WIDTHS = [
    ("opcode", 3), ("param", 2), ("size", 3), ("source", 4),
    ("data", None), ("valid", 1),
]


def _wdecl(width):
    return "" if width == 1 else f"[{width-1}:0] "


def _abits(depth):
    return max(1, (depth - 1).bit_length())


def gen_noc_mesh(spec):
    name = spec.get("name", "noc_mesh")
    nx = int(spec["mesh_nx"])
    ny = int(spec["mesh_ny"])
    dw = int(spec.get("data_width", 64))       # router/SRAM internal TL data width
    aw = int(spec.get("addr_width", 32))       # global mesh address width
    ext_dw = int(spec.get("ext_data_width", 32))  # per-node NI-facing AXI data width
    sram_depth = int(spec.get("sram_depth", 1024))
    sw = dw // 8
    ext_sw = ext_dw // 8
    ab = _abits(sram_depth)

    router_fmt = spec.get("router_name_fmt", "u_router_{x}{y}")
    ni_fmt = spec.get("ni_name_fmt", "u_ni_{x}{y}")
    sram_fmt = spec.get("sram_name_fmt", "u_sram_{x}{y}")

    def rname(x, y): return router_fmt.format(x=x, y=y)
    def niname(x, y): return ni_fmt.format(x=x, y=y)
    def sname(x, y): return sram_fmt.format(x=x, y=y)
    def nid(x, y): return f"{x}{y}"

    a_widths = {"opcode": 3, "param": 3, "size": 3, "source": 4,
                "addr": aw, "mask": sw, "data": dw, "valid": 1}
    d_widths = {"opcode": 3, "param": 2, "size": 3, "source": 4,
                "data": dw, "valid": 1}
    # The loc_a_* wires between NI and router are DRIVEN BY the NI (NI's
    # tl_a_data/tl_a_mask are its outputs). NI's own data/mask widths are
    # narrower than the router's (ext_dw/ext_sw vs dw/sw) - if the wire were
    # declared at the router's wider width, NI would only drive the low bits
    # and the upper bits would be left permanently undriven ('x'), NOT
    # zero-extended (verified: this is exactly what happened in the first
    # real 2x2-mesh simulation attempt - sram_11.mem[3] read back as
    # xxxxxxxxcafebabe). Declaring the wire at NI's actual (narrower) output
    # width instead makes the ROUTER's wider input port correctly
    # zero-extend on read, which IS well-defined Verilog behavior for an
    # input port sized larger than the net feeding it.
    a_widths_ni = dict(a_widths)
    a_widths_ni["mask"] = ext_sw
    a_widths_ni["data"] = ext_dw

    lines = []          # module body
    wire_decls = []      # all local wire declarations, collected up front
    inst_lines = []      # all instantiations

    # ---- external per-node AXI4-Lite slave ports ----
    ext_ports = []
    for y in range(ny):
        for x in range(nx):
            nn = nid(x, y)
            ext_ports.append(
                f"    input  wire [{aw-1}:0] n{nn}_awaddr, input wire n{nn}_awvalid, output wire n{nn}_awready,\n"
                f"    input  wire [{ext_dw-1}:0] n{nn}_wdata, input wire [{ext_sw-1}:0] n{nn}_wstrb,\n"
                f"    input  wire n{nn}_wvalid, output wire n{nn}_wready,\n"
                f"    output wire [1:0] n{nn}_bresp, output wire n{nn}_bvalid, input wire n{nn}_bready,\n"
                f"    input  wire [{aw-1}:0] n{nn}_araddr, input wire n{nn}_arvalid, output wire n{nn}_arready,\n"
                f"    output wire [{ext_dw-1}:0] n{nn}_rdata, output wire [1:0] n{nn}_rresp,\n"
                f"    output wire n{nn}_rvalid, input wire n{nn}_rready,"
            )
    ports_block = "\n".join(ext_ports)
    last_comma = ports_block.rfind(",")
    ports_block = ports_block[:last_comma] + ports_block[last_comma + 1:]

    code = _hdr(name, f"Deterministic {nx}x{ny} NoC mesh stitch (router+NI+SRAM "
                       f"wiring is generated, not LLM-authored) - internal TL "
                       f"data={dw}b addr={aw}b, per-node external AXI data={ext_dw}b")
    code += f"module {name} (\n    input wire clk, rst_n,\n{ports_block}\n);\n\n"

    # ---- per-node: local port <-> NI, sram port <-> SRAM ----
    for y in range(ny):
        for x in range(nx):
            nn = nid(x, y)
            # loc_a_* / loc_d_* wires between router and NI
            for fld, w in a_widths_ni.items():
                wire_decls.append(f"    wire {_wdecl(w)}loc_{nn}_a_{fld};")
            wire_decls.append(f"    wire loc_{nn}_a_ready;")
            for fld, w in d_widths.items():
                wire_decls.append(f"    wire {_wdecl(w)}loc_{nn}_d_{fld};")
            wire_decls.append(f"    wire loc_{nn}_d_ready;")

            # sram AXI wires between router's embedded master and the SRAM instance
            wire_decls.append(f"    wire [{aw-1}:0] sram_{nn}_awaddr, sram_{nn}_araddr;")
            wire_decls.append(f"    wire sram_{nn}_awvalid, sram_{nn}_awready;")
            wire_decls.append(f"    wire [{dw-1}:0] sram_{nn}_wdata; wire [{sw-1}:0] sram_{nn}_wstrb;")
            wire_decls.append(f"    wire sram_{nn}_wvalid, sram_{nn}_wready;")
            wire_decls.append(f"    wire [1:0] sram_{nn}_bresp; wire sram_{nn}_bvalid, sram_{nn}_bready;")
            wire_decls.append(f"    wire sram_{nn}_arvalid, sram_{nn}_arready;")
            wire_decls.append(f"    wire [{dw-1}:0] sram_{nn}_rdata; wire [1:0] sram_{nn}_rresp;")
            wire_decls.append(f"    wire sram_{nn}_rvalid, sram_{nn}_rready;")

            inst_lines.append(f"""\
    {niname(x,y)} {niname(x,y)} (
        .clk(clk), .rst_n(rst_n),
        .axi_awaddr(n{nn}_awaddr), .axi_awvalid(n{nn}_awvalid), .axi_awready(n{nn}_awready),
        .axi_wdata(n{nn}_wdata), .axi_wstrb(n{nn}_wstrb), .axi_wvalid(n{nn}_wvalid), .axi_wready(n{nn}_wready),
        .axi_bresp(n{nn}_bresp), .axi_bvalid(n{nn}_bvalid), .axi_bready(n{nn}_bready),
        .axi_araddr(n{nn}_araddr), .axi_arvalid(n{nn}_arvalid), .axi_arready(n{nn}_arready),
        .axi_rdata(n{nn}_rdata), .axi_rresp(n{nn}_rresp), .axi_rvalid(n{nn}_rvalid), .axi_rready(n{nn}_rready),
        .tl_a_opcode(loc_{nn}_a_opcode), .tl_a_param(loc_{nn}_a_param), .tl_a_size(loc_{nn}_a_size),
        .tl_a_source(loc_{nn}_a_source), .tl_a_addr(loc_{nn}_a_addr), .tl_a_mask(loc_{nn}_a_mask),
        .tl_a_data(loc_{nn}_a_data), .tl_a_valid(loc_{nn}_a_valid), .tl_a_ready(loc_{nn}_a_ready),
        .tl_d_opcode(loc_{nn}_d_opcode), .tl_d_param(loc_{nn}_d_param), .tl_d_size(loc_{nn}_d_size),
        .tl_d_source(loc_{nn}_d_source), .tl_d_data(loc_{nn}_d_data), .tl_d_valid(loc_{nn}_d_valid),
        .tl_d_ready(loc_{nn}_d_ready)
    );

    {sname(x,y)} {sname(x,y)} (
        .aclk(clk), .aresetn(rst_n),
        .awaddr(sram_{nn}_awaddr[{ab-1}:0]), .awvalid(sram_{nn}_awvalid), .awready(sram_{nn}_awready),
        .wdata(sram_{nn}_wdata), .wstrb(sram_{nn}_wstrb), .wvalid(sram_{nn}_wvalid), .wready(sram_{nn}_wready),
        .bresp(sram_{nn}_bresp), .bvalid(sram_{nn}_bvalid), .bready(sram_{nn}_bready),
        .araddr(sram_{nn}_araddr[{ab-1}:0]), .arvalid(sram_{nn}_arvalid), .arready(sram_{nn}_arready),
        .rdata(sram_{nn}_rdata), .rresp(sram_{nn}_rresp), .rvalid(sram_{nn}_rvalid), .rready(sram_{nn}_rready)
    );
""")

    # ---- inter-router links: for every adjacent pair, wire BOTH directions ----
    # compass convention (matches gen_router_v2.py): p0=N p1=S p2=E p3=W
    link_wire_decls = []
    router_link_ports = {nid(x, y): {} for y in range(ny) for x in range(nx)}  # nid -> {portname: wirename}

    def declare_link(a_x, a_y, a_port, b_x, b_y, b_port):
        """a's p{a_port}_m_* (master, sending) <-> b's p{b_port}_s_* (slave, receiving),
        plus the D-channel reply flowing back from b to a on the same bundle."""
        a_n, b_n = nid(a_x, a_y), nid(b_x, b_y)
        base = f"lnk_{a_n}_{a_port}_to_{b_n}_{b_port}"
        for fld, w in a_widths.items():
            link_wire_decls.append(f"    wire {_wdecl(w)}{base}_a_{fld};")
        link_wire_decls.append(f"    wire {base}_a_ready;")
        for fld, w in d_widths.items():
            link_wire_decls.append(f"    wire {_wdecl(w)}{base}_d_{fld};")
        link_wire_decls.append(f"    wire {base}_d_ready;")
        router_link_ports[a_n][f"p{a_port}_m"] = base
        router_link_ports[b_n][f"p{b_port}_s"] = base

    for y in range(ny):
        for x in range(nx):
            if x + 1 < nx:
                # (x,y) East(p2) <-> (x+1,y) West(p3)
                declare_link(x, y, 2, x + 1, y, 3)   # (x,y) -> (x+1,y), eastbound
                declare_link(x + 1, y, 3, x, y, 2)   # (x+1,y) -> (x,y), westbound
            if y + 1 < ny:
                # (x,y) North(p0) <-> (x,y+1) South(p1)
                declare_link(x, y, 0, x, y + 1, 1)   # (x,y) -> (x,y+1), northbound
                declare_link(x, y + 1, 1, x, y, 0)   # (x,y+1) -> (x,y), southbound

    # ---- router instantiations ----
    router_insts = []
    for y in range(ny):
        for x in range(nx):
            nn = nid(x, y)
            links = router_link_ports[nn]
            port_conns = []
            port_conns.append(f".clk(clk), .rst_n(rst_n)")
            port_conns.append(
                f".loc_a_opcode(loc_{nn}_a_opcode), .loc_a_param(loc_{nn}_a_param), .loc_a_size(loc_{nn}_a_size),\n"
                f"        .loc_a_source(loc_{nn}_a_source), .loc_a_addr(loc_{nn}_a_addr), .loc_a_mask(loc_{nn}_a_mask),\n"
                f"        .loc_a_data(loc_{nn}_a_data), .loc_a_valid(loc_{nn}_a_valid), .loc_a_ready(loc_{nn}_a_ready),\n"
                f"        .loc_d_opcode(loc_{nn}_d_opcode), .loc_d_param(loc_{nn}_d_param), .loc_d_size(loc_{nn}_d_size),\n"
                f"        .loc_d_source(loc_{nn}_d_source), .loc_d_data(loc_{nn}_d_data), .loc_d_valid(loc_{nn}_d_valid),\n"
                f"        .loc_d_ready(loc_{nn}_d_ready)"
            )
            port_conns.append(
                f".sram_awaddr(sram_{nn}_awaddr), .sram_awvalid(sram_{nn}_awvalid), .sram_awready(sram_{nn}_awready),\n"
                f"        .sram_wdata(sram_{nn}_wdata), .sram_wstrb(sram_{nn}_wstrb), .sram_wvalid(sram_{nn}_wvalid), .sram_wready(sram_{nn}_wready),\n"
                f"        .sram_bresp(sram_{nn}_bresp), .sram_bvalid(sram_{nn}_bvalid), .sram_bready(sram_{nn}_bready),\n"
                f"        .sram_araddr(sram_{nn}_araddr), .sram_arvalid(sram_{nn}_arvalid), .sram_arready(sram_{nn}_arready),\n"
                f"        .sram_rdata(sram_{nn}_rdata), .sram_rresp(sram_{nn}_rresp), .sram_rvalid(sram_{nn}_rvalid), .sram_rready(sram_{nn}_rready)"
            )
            for i in range(4):
                s_key, m_key = f"p{i}_s", f"p{i}_m"
                if s_key in links:
                    base = links[s_key]
                    port_conns.append(
                        f".p{i}_s_a_opcode({base}_a_opcode), .p{i}_s_a_param({base}_a_param), .p{i}_s_a_size({base}_a_size),\n"
                        f"        .p{i}_s_a_source({base}_a_source), .p{i}_s_a_addr({base}_a_addr), .p{i}_s_a_mask({base}_a_mask),\n"
                        f"        .p{i}_s_a_data({base}_a_data), .p{i}_s_a_valid({base}_a_valid), .p{i}_s_a_ready({base}_a_ready),\n"
                        f"        .p{i}_s_d_opcode({base}_d_opcode), .p{i}_s_d_param({base}_d_param), .p{i}_s_d_size({base}_d_size),\n"
                        f"        .p{i}_s_d_source({base}_d_source), .p{i}_s_d_data({base}_d_data), .p{i}_s_d_valid({base}_d_valid),\n"
                        f"        .p{i}_s_d_ready({base}_d_ready)"
                    )
                else:
                    port_conns.append(
                        f".p{i}_s_a_opcode(3'b0), .p{i}_s_a_param(3'b0), .p{i}_s_a_size(3'b0),\n"
                        f"        .p{i}_s_a_source(4'b0), .p{i}_s_a_addr({aw}'b0), .p{i}_s_a_mask({sw}'b0),\n"
                        f"        .p{i}_s_a_data({dw}'b0), .p{i}_s_a_valid(1'b0), .p{i}_s_a_ready(),\n"
                        f"        .p{i}_s_d_opcode(), .p{i}_s_d_param(), .p{i}_s_d_size(),\n"
                        f"        .p{i}_s_d_source(), .p{i}_s_d_data(), .p{i}_s_d_valid(),\n"
                        f"        .p{i}_s_d_ready(1'b0)"
                    )
                if m_key in links:
                    base = links[m_key]
                    port_conns.append(
                        f".p{i}_m_a_opcode({base}_a_opcode), .p{i}_m_a_param({base}_a_param), .p{i}_m_a_size({base}_a_size),\n"
                        f"        .p{i}_m_a_source({base}_a_source), .p{i}_m_a_addr({base}_a_addr), .p{i}_m_a_mask({base}_a_mask),\n"
                        f"        .p{i}_m_a_data({base}_a_data), .p{i}_m_a_valid({base}_a_valid), .p{i}_m_a_ready({base}_a_ready),\n"
                        f"        .p{i}_m_d_opcode({base}_d_opcode), .p{i}_m_d_param({base}_d_param), .p{i}_m_d_size({base}_d_size),\n"
                        f"        .p{i}_m_d_source({base}_d_source), .p{i}_m_d_data({base}_d_data), .p{i}_m_d_valid({base}_d_valid),\n"
                        f"        .p{i}_m_d_ready({base}_d_ready)"
                    )
                else:
                    port_conns.append(
                        f".p{i}_m_a_opcode(), .p{i}_m_a_param(), .p{i}_m_a_size(),\n"
                        f"        .p{i}_m_a_source(), .p{i}_m_a_addr(), .p{i}_m_a_mask(),\n"
                        f"        .p{i}_m_a_data(), .p{i}_m_a_valid(), .p{i}_m_a_ready(1'b0),\n"
                        f"        .p{i}_m_d_opcode(3'b0), .p{i}_m_d_param(2'b0), .p{i}_m_d_size(3'b0),\n"
                        f"        .p{i}_m_d_source(4'b0), .p{i}_m_d_data({dw}'b0), .p{i}_m_d_valid(1'b0),\n"
                        f"        .p{i}_m_d_ready()"
                    )
            router_insts.append(
                f"    {rname(x,y)} #(.NODE_X({x}), .NODE_Y({y}), .DATA_W({dw}), .ADDR_W({aw})) {rname(x,y)} (\n        "
                + ",\n        ".join(port_conns) + "\n    );\n"
            )

    code += "    // ---- per-node local wires (router<->NI, router<->SRAM) ----\n"
    code += "\n".join(wire_decls) + "\n\n"
    code += "    // ---- inter-router link wires (both directions of every physical link) ----\n"
    code += "\n".join(link_wire_decls) + "\n\n"
    code += "    // ---- per-node NI + SRAM instances ----\n"
    code += "\n".join(inst_lines) + "\n"
    code += "    // ---- router instances ----\n"
    code += "\n".join(router_insts) + "\n"
    code += "endmodule\n"

    return {f"{name}.v": code}


if __name__ == "__main__":
    spec = {"name": "noc_mesh_2x2_test", "mesh_nx": 2, "mesh_ny": 2,
            "data_width": 64, "addr_width": 32, "ext_data_width": 32, "sram_depth": 1024}
    files = gen_noc_mesh(spec)
    for fname, content in files.items():
        with open(fname, "w") as f:
            f.write(content)
        print(f"Wrote {fname} ({len(content)} chars)")
